config/routes.rb
Karma::Application.routes.draw do

	namespace :api, :defaults => {:format => :json} do
		resources :entries
	end

  resources :entries
	resources :tenants


	#match '/' => 'dashboards#show', :constraints => { :subdomain => /.+/ }, via: [:get]
	match '', to: 'dashboards#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }, via: [:get]

	#constraints(Subdomain) do  
  #  match '/' => 'dashboards#show', via: [:get] 
  #end 

  root  'custom_pages#home'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	scope :find_by_subdomain, ->(subdomain_param) { where("lower(subdomain) = ?", subdomain_param.downcase).first }

	before_save { |tenant| tenant.subdomain = subdomain.downcase }
end

app/controllers/api/entries_controller.rb
class API::EntriesController < ApplicationController
	respond_to :json

	def index
		respond_with Entry.paginate(page: params[:page], :per_page => 10)
	end

	def show 
		respond_with Entry.find(params[:id])
	end

	def create
		respond_with Entry.create(entry_params)
	end

	def update
		respond_with Entry.update(params[:id], entry_params)
	end

	def destroy
		respond_with Entry.destroy(params[:id])
	end


  private

    def entry_params
      params.require(:entry).permit(:name, :winner)
    end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper  
end

app/controllers/custom_pages_controller.rb
class CustomPagesController < ApplicationController
  def home
    
  end		
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  	puts request.subdomain
    @tenant = Tenant.find_by_subdomain!(request.subdomain)	
  end	
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController


	def index
		@entries = Entry.all
	end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = Tenant.paginate(page: params[:page], :per_page => 10)
  end		

  def show
    @tenant = Tenant.find(params[:id])	
  end

  def new
  	@tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    
    if @tenant.save     
      flash[:success] = "The new tenant has been created."
      
      redirect_to @tenant
    else
      render 'new'
    end
  end

  def edit
		@tenant = Tenant.find(params[:id])	
  end  

  def update
		@tenant = Tenant.find(params[:id])	

    if @tenant.update_attributes(tenant_params)
      flash[:success] = "Profile updated"
      redirect_to @tenant
    else
      render 'edit'
    end
  end   

  def destroy
    
    @tenant = Tenant.find(params[:id])    
    @tenant.destroy
    
    respond_to do |format|      
      format.js
    end    
  end   

  private

    def tenant_params
      params.require(:tenant).permit(:name, :subdomain)
    end
 
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Karma"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/custom_pages_helper.rb
module CustomPagesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end  

  def current_user?(user)
    user == current_user
  end  

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end  

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end  
end

app/views/custom_pages/home.html.erb
<!-- if signed_in? -->
<% if 1 != 1 %>
  <div class="row">
    TODO: User Dashboard Goes Here.
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to my test page</h1>

    <h2>
      This is the home page for testing a variety of paging methods     
    </h2>

    <div>
      <%= link_to "Paging", tenants_path %>
    </div>

    <div>
      <%= link_to "Infinite Scrolling", entries_path, data: { type: :html} %>
    </div>

  </div>

<% end %>

app/views/dashboards/show.html.erb
    <div class="row">
	    <div class="form-inline span11">  
			  <%= content_tag(:div) do content_tag(:b,"Name: ") + @tenant.name end %> 
			  <%= content_tag(:div) do content_tag(:b,"Subdomain: ") + @tenant.subdomain end %>
			</div>
		</div>

		<br><br>
		<div class="row">
			Widgets go Here.
		</div>

app/views/entries/index.html.erb
<h1>All Entries</h1>


<br><br>


<div ng-controller="SampleCtrl">

	<form ng-submit="addEntry()">
		<input type="text" ng-model="newEntry.name">
		<input type="submit" value="Add">
	</form>

	<ul infinite-scroll="paging.nextPage()" infinite-scroll-disabled='paging.busy' infinite-scroll-distance="1">
		<li ng-repeat="entry in paging.items">
			{{entry.name}}
			<span ng-show="entry.winner" ng-class="{highlight: entry == lastWinner}" class="winner">Winner</span>
		</li>
		<div ng-show="paging.busy">Loading data...</div>
</ul>

	<button ng-click="drawWinner()">Draw Winner</button>

</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
 
   
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Karma", root_url(:subdomain => false), id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>          
          
        </ul>
      </nav>
    </div>
  </div>
</header>

<%= image_tag("ajax-loader.gif", :class => "loading-indicator", :id => "imgAjaxLoader") %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Raffler">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div class="row" id="tenant_<%= tenant.id %>">  
	<div class="span3"><%= link_to tenant.name, tenant_path(tenant) %></div>
	<div class="span3">Subdomain: <%= tenant.subdomain %></div>

  &nbsp&nbsp&nbsp&nbsp
	<%= link_to "View", root_url(:subdomain => tenant.subdomain) %>	 

  &nbsp&nbsp&nbsp&nbsp
	<%= link_to "Delete", tenant, method: :delete,
		                data: { confirm: "Are you sure?" }, remote: true %>
</div>

app/views/tenants/_tenant_fields.html.erb
    <%= nested_form_for @tenant, :html => {:multipart => true} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="row">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: 'span6' %>
      </div>

      <div class="row">
        <%= f.label :subdomain, "Subdomain" %>
        <%= f.text_field :subdomain, class: 'span6' %>
      </div>

      <div class="row">
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

        <% if @tenant.id.blank? %>
          <%= link_to "Cancel", tenants_path,  method: :get, class: "btn btn-large" %>
        <% else %>
          <%= link_to "Cancel", tenant_path(@tenant),  method: :get, class: "btn btn-large" %>
        <% end %>
      </div>
      
            
    <% end %>      

app/views/tenants/destroy.js.erb

$("#tenant_<%= @tenant.id %>").hide();

app/views/tenants/edit.html.erb
<h1>Tenant Information</h1>

<div class="row">
  <div class="span8">   
    <%= render 'tenants/tenant_fields' %>
  </div>
</div>

app/views/tenants/index.html.erb
<h1>All Tenants</h1>

<div class="row">
<%= link_to "Create a Tenant", new_tenant_path, class: "btn btn-large btn-primary" %>
</div>

<br><br>

<%= will_paginate %>

<ul>
  <%= render @tenants %>
</ul>

<%= will_paginate %>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<div class="row">
  <div class="span8">
    <%= render 'tenants/tenant_fields' %>

  </div>
</div>

app/views/tenants/show.html.erb
    <div class="row">
	    <div class="form-inline span11">  
			  <%= content_tag(:div) do content_tag(:b,"Name: ") + @tenant.name end %> 
			  <%= content_tag(:div) do content_tag(:b,"Subdomain: ") + @tenant.subdomain end %>
			</div>
		</div>

		<br><br>
		<div class="row">
			<%= link_to "Edit", edit_tenant_path(@tenant.id), class: "btn btn-large btn-primary" %>	
		</div>